Stop tracebacks if vendor_specific is not set
My ipxe client is sending vendor_class_identifier but not
vendor_specific which leads to a exception when serving dhcp:

AttributeError: 'NoneType' object has no attribute 'items'

Wrap the extractiong of vendor_specific with a check to see if it
exists instead of a check to see if vendor_class_identifier exists.